Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,22 +8,27 @@ on:
 jobs:
   set-deploy-type:
     runs-on: ubuntu-latest
+    env:
+      VALID_TARGETS: "gh-pages firebase"
     steps:
       - uses: actions/checkout@v2
 
       - name: get deployment target
-        run: TARGET=$(cat DEPLOY_STRATEGY)
+        run: |
+          TARGET=$(cat DEPLOY_STRATEGY)
+          echo $TARGET >> $GITHUB_ENV
 
       - name: check if target is valid
-        if: !contains(['gh-pages', 'firebase'], env.TARGET)
         run: |
-          echo 'Invalid Deployment Target'
-          exit 1
+          if ! echo $VALID_TARGETS | grep -w ${{ env.TARGET }}; then
+            echo 'Invalid Deployment Target'
+            exit 1
+          fi
 
   deploy-gh-pages:
     runs-on: ubuntu-latest
     needs: set-deploy-type
-    if: $TARGET == 'gh-pages'
+    if: env.TARGET == 'gh-pages'
 
     steps:
     - uses: actions/checkout@v2
@@ -38,7 +43,7 @@ jobs:
   deploy-firebase:
     runs-on: ubuntu-latest
     needs: set-deploy-type
-    if: $TARGET == 'firebase'
+    if: env.TARGET == 'firebase'
 
     steps:
     - uses: actions/checkout@v2
